Repository jenkins-infra/account-app, pull requests merged in 2022-11, with the labels that each got.

#181 Add reset password tests
  .gitignore
  Jenkinsfile
  README.md
  build.gradle.kts
  docker-compose.yaml
  src/it/java/org/jenkinsci/account/ui/BaseTest.java
  src/it/java/org/jenkinsci/account/ui/admin/AdminPage.java
  src/it/java/org/jenkinsci/account/ui/admin/AdminResetPasswordResultPage.java
  src/it/java/org/jenkinsci/account/ui/admin/AdminSearchPage.java
  src/it/java/org/jenkinsci/account/ui/admin/ResetPasswordAdminTest.java
  src/it/java/org/jenkinsci/account/ui/email/Emails.java
  src/it/java/org/jenkinsci/account/ui/email/ReadInboundEmailService.java
  src/it/java/org/jenkinsci/account/ui/login/LoginPage.java
  src/it/java/org/jenkinsci/account/ui/login/LoginTest.java
  src/it/java/org/jenkinsci/account/ui/myaccount/MyAccountPage.java
  src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordPage.java
  src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordTest.java
  src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordType.java
  src/it/resources/org/jenkinsci/account/ui/test-data.ldif
  src/main/java/org/jenkinsci/account/Application.java
  src/main/java/org/jenkinsci/account/Parameters.java
  src/main/java/org/jenkinsci/account/WebAppMain.java
  src/main/java/org/jenkinsci/account/config/MailConfig.java
  src/main/resources/application.conf
  src/main/resources/org/jenkinsci/account/AdminUI/newPassword.jelly
Labels: tests

#189 Add delete user and self service update tests
  build.gradle.kts
  src/it/java/org/jenkinsci/account/ui/BaseTest.java
  src/it/java/org/jenkinsci/account/ui/admin/AdminPage.java
  src/it/java/org/jenkinsci/account/ui/admin/DeleteUserTest.java
  src/it/java/org/jenkinsci/account/ui/admin/ResetPasswordAdminTest.java
  src/it/java/org/jenkinsci/account/ui/myaccount/MyProfilePage.java
  src/it/java/org/jenkinsci/account/ui/myaccount/UpdateMyAccountTest.java
  src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordTest.java
  src/it/java/org/jenkinsci/account/ui/resetpassword/UserLookupType.java
  src/main/java/org/jenkinsci/account/Myself.java
Labels: tests

#191 Remove signup survey
  src/main/java/org/jenkinsci/account/Application.java
  src/main/resources/org/jenkinsci/account/Application/signup.jelly
Labels: enhancement

#192 Fix email field signup spacing
  src/main/resources/org/jenkinsci/account/Application/signup.jelly
Labels: bug

#190 Upgrade to Jetty 10, Java 17, Jakarta dependencies
  Dockerfile
  Jenkinsfile
  build.gradle.kts
  settings.gradle.kts
  src/it/java/org/jenkinsci/account/ui/admin/ResetPasswordAdminTest.java
  src/it/java/org/jenkinsci/account/ui/email/ReadInboundEmailService.java
  src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordTest.java
  src/main/java/org/jenkinsci/account/AdminUI.java
  src/main/java/org/jenkinsci/account/Application.java
Labels: enhancement

#195 Bump botdetect-jsp20 from beta3.0 to beta3.7
  build.gradle.kts
Labels: dependencies
