Repository jenkins-infra/account-app, pull requests merged in 2022-10, with the labels that each got.

#148 All the dependencies are needed at runtime too
  Dockerfile
  build.gradle.kts
Labels: bug

#146 Refresh UI
  build.gradle.kts
  src/main/java/org/jenkinsci/account/Application.java
  src/main/java/org/jenkinsci/account/openid/JenkinsOpenIDSession.java
  src/main/resources/org/jenkinsci/account/AdminUI/index.jelly
  src/main/resources/org/jenkinsci/account/AdminUI/search.jelly
  src/main/resources/org/jenkinsci/account/AdminUI/signup.jelly
  src/main/resources/org/jenkinsci/account/Application/doneMail.jelly
  src/main/resources/org/jenkinsci/account/Application/index.jelly
  src/main/resources/org/jenkinsci/account/Application/login.jelly
  src/main/resources/org/jenkinsci/account/Application/passwordReset.jelly
  src/main/resources/org/jenkinsci/account/Application/signup.jelly
  src/main/resources/org/jenkinsci/account/Myself/index.jelly
  src/main/resources/org/jenkinsci/account/taglib/layout.jelly
  src/main/webapp/logo.svg
  src/main/webapp/style.css
Labels: enhancement

#145 Add renovate
  renovate.json
Labels: chore

#144 Add CI
  Jenkinsfile
  config.properties.example
Labels: bug

#170 chore(Dockerfile) correct the DD_AGENT download
  Dockerfile
Labels: bug

#171 fix: Make renovate work again
  renovate.json
Labels: chore

#168 Use a mail implementation not api
  build.gradle.kts
Labels: bug

#175 Introduce config library
  Dockerfile
  Makefile
  README.md
  build.gradle.kts
  config.properties.example
  docker-compose.yaml
  entrypoint.sh
  env.sandbox
  src/main/java/org/jenkinsci/account/Application.java
  src/main/java/org/jenkinsci/account/Parameters.java
  src/main/java/org/jenkinsci/account/WebAppMain.java
  src/main/java/org/jenkinsci/account/config/LdapConfig.java
  src/main/java/org/jenkinsci/account/config/MailConfig.java
  src/main/resources/application.conf
Labels: enhancement

#167 Initial UI test to make sure login works
  Dockerfile
  Jenkinsfile
  build.gradle.kts
  src/it/java/org/jenkinsci/account/ui/BaseTest.java
  src/it/java/org/jenkinsci/account/ui/LoginPage.java
  src/it/java/org/jenkinsci/account/ui/LoginTest.java
  src/it/resources/org/jenkinsci/account/ui/test-data.ldif
Labels: tests
